version: '3'

services:
  mock:
    build: ./mockdb
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    expose:
      - '5432'
    volumes:
      - postgres:/var/lib/postgres
    ports:
      - '5432:5432'

volumes:
  postgres:
